<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://webservice" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://webservice" xmlns:intf="http://webservice" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://webservice" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="returnHello">
    <complexType/>
   </element>
   <element name="returnHelloResponse">
    <complexType>
     <sequence>
      <element name="returnHelloReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="returnHelloResponse">

      <wsdl:part element="impl:returnHelloResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="returnHelloRequest">

      <wsdl:part element="impl:returnHello" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="FirstServer">

      <wsdl:operation name="returnHello">

         <wsdl:input message="impl:returnHelloRequest" name="returnHelloRequest">

       </wsdl:input>

         <wsdl:output message="impl:returnHelloResponse" name="returnHelloResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="FirstServerSoapBinding" type="impl:FirstServer">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="returnHello">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="returnHelloRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="returnHelloResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="FirstServerService">

      <wsdl:port binding="impl:FirstServerSoapBinding" name="FirstServer">

         <wsdlsoap:address location="http://tempuri.org/webservice/services/FirstServer"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
